#!/usr/bin/env bash
# 在固定版本的 emsdk 容器里构建只含 FFmpeg TrueHD 解码器的 WASM，产物写入 wasm/truehd-wasm.mjs。
# 产物随仓库提交，日常 pnpm build 不需要 Docker；只有升级 FFmpeg、Emscripten 或改动 native/bridge.c 时才重跑。
set -euo pipefail

FFMPEG_VERSION=9.0.2
FFMPEG_SHA256=8c3850283eb25fa026482078a04051e0be17347b09ef81a0849bec15a96e002e
EMSDK_IMAGE=emscripten/emsdk:6.0.10@sha256:e077d54e2b8970575ebc4f185ac1de0b95c05f2b266134d4ba27449af7aebf65

package_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache_root="${SHIMWEAVE_TRUEHD_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/shimweave-truehd}"
mkdir -p "$cache_root"

docker run --rm \
  --user "$(id -u):$(id -g)" \
  -e HOME=/tmp \
  -e FFMPEG_VERSION="$FFMPEG_VERSION" \
  -e FFMPEG_SHA256="$FFMPEG_SHA256" \
  -v "$package_root:/package" \
  -v "$cache_root:/cache" \
  "$EMSDK_IMAGE" \
  bash -euo pipefail -c '
    tarball="/cache/ffmpeg-$FFMPEG_VERSION.tar.xz"
    if [ ! -f "$tarball" ]; then
      curl -fsSL -o "$tarball.part" "https://ffmpeg.org/releases/ffmpeg-$FFMPEG_VERSION.tar.xz"
      mv "$tarball.part" "$tarball"
    fi
    echo "$FFMPEG_SHA256  $tarball" | sha256sum -c -

    work=/tmp/build
    rm -rf "$work" && mkdir -p "$work"
    tar -xJf "$tarball" -C "$work"
    source_dir="$work/ffmpeg-$FFMPEG_VERSION"

    cd "$source_dir"
    emconfigure ./configure \
      --target-os=none \
      --arch=x86_32 \
      --enable-cross-compile \
      --disable-asm \
      --disable-x86asm \
      --disable-inline-asm \
      --disable-programs \
      --disable-doc \
      --disable-debug \
      --disable-all \
      --disable-everything \
      --disable-autodetect \
      --disable-pthreads \
      --disable-runtime-cpudetect \
      --disable-network \
      --enable-small \
      --enable-avcodec \
      --enable-decoder=truehd \
      --cc=emcc \
      --cxx=em++ \
      --ar=emar \
      --ranlib=emranlib \
      --extra-cflags="-DNDEBUG -Oz -flto -msimd128" \
      --extra-ldflags="-Oz -flto" >/dev/null
    emmake make -j"$(nproc)" >/dev/null

    emcc /package/native/bridge.c \
      libavcodec/libavcodec.a \
      libavutil/libavutil.a \
      -I"$source_dir" \
      -s MODULARIZE=1 \
      -s EXPORT_ES6=1 \
      -s EXPORT_NAME=createTrueHdModule \
      -s SINGLE_FILE=1 \
      -s ALLOW_MEMORY_GROWTH=1 \
      -s ENVIRONMENT=web,worker \
      -s FILESYSTEM=0 \
      -s MALLOC=emmalloc \
      -s SUPPORT_LONGJMP=0 \
      -s EXPORTED_RUNTIME_METHODS=cwrap,HEAPU8,HEAPF32,UTF8ToString \
      -s EXPORTED_FUNCTIONS=_malloc,_free \
      -msimd128 \
      -flto \
      -Oz \
      -o /tmp/truehd-wasm.mjs

    # 另链一份独立 .wasm 只用于报告体积，不提交。
    mkdir -p /tmp/measure
    emcc /package/native/bridge.c libavcodec/libavcodec.a libavutil/libavutil.a -I"$source_dir" \
      -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web,worker -s FILESYSTEM=0 -s MALLOC=emmalloc \
      -s SUPPORT_LONGJMP=0 -s EXPORTED_RUNTIME_METHODS=cwrap,HEAPU8,HEAPF32,UTF8ToString \
      -s EXPORTED_FUNCTIONS=_malloc,_free -msimd128 -flto -Oz -o /tmp/measure/truehd.mjs
    raw=$(stat -c %s /tmp/measure/truehd.wasm)
    gz=$(gzip -9c /tmp/measure/truehd.wasm | wc -c)

    {
      echo "// Generated by scripts/build-wasm.sh from FFmpeg $FFMPEG_VERSION (LGPL-2.1-or-later). Do not edit."
      cat /tmp/truehd-wasm.mjs
    } >/package/wasm/truehd-wasm.mjs
    echo "wasm raw=${raw}B gzip=${gz}B, glue with inlined wasm=$(stat -c %s /package/wasm/truehd-wasm.mjs)B"
  '
